package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AddressType generated by hbm2java
 */
@Entity
@Table(name = "address_type", catalog = "carservice")
public class AddressType implements java.io.Serializable {

	private Integer addressTypeId;
	private String addressTypeName;
	private Set<EmployeeAddress> employeeAddresses = new HashSet<EmployeeAddress>(0);
	private Set<CustomerAddress> customerAddresses = new HashSet<CustomerAddress>(0);

	public AddressType() {
	}

	public AddressType(String addressTypeName, Set<EmployeeAddress> employeeAddresses,
			Set<CustomerAddress> customerAddresses) {
		this.addressTypeName = addressTypeName;
		this.employeeAddresses = employeeAddresses;
		this.customerAddresses = customerAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ADDRESS_TYPE_ID", unique = true, nullable = false)
	public Integer getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(Integer addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	@Column(name = "ADDRESS_TYPE_NAME", length = 50)
	public String getAddressTypeName() {
		return this.addressTypeName;
	}

	public void setAddressTypeName(String addressTypeName) {
		this.addressTypeName = addressTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressType")
	public Set<EmployeeAddress> getEmployeeAddresses() {
		return this.employeeAddresses;
	}

	public void setEmployeeAddresses(Set<EmployeeAddress> employeeAddresses) {
		this.employeeAddresses = employeeAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressType")
	public Set<CustomerAddress> getCustomerAddresses() {
		return this.customerAddresses;
	}

	public void setCustomerAddresses(Set<CustomerAddress> customerAddresses) {
		this.customerAddresses = customerAddresses;
	}

}
