package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", catalog = "carservice")
public class City implements java.io.Serializable {

	private int cityId;
	private State state;
	private String cityName;
	private Set<CustomerAddress> customerAddresses = new HashSet<CustomerAddress>(0);
	private Set<EmployeeAddress> employeeAddresses = new HashSet<EmployeeAddress>(0);

	public City() {
	}

	public City(int cityId) {
		this.cityId = cityId;
	}

	public City(int cityId, State state, String cityName, Set<CustomerAddress> customerAddresses,
			Set<EmployeeAddress> employeeAddresses) {
		this.cityId = cityId;
		this.state = state;
		this.cityName = cityName;
		this.customerAddresses = customerAddresses;
		this.employeeAddresses = employeeAddresses;
	}

	@Id

	@Column(name = "CITY_ID", unique = true, nullable = false)
	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATE_ID")
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}

	@Column(name = "CITY_NAME", length = 50)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<CustomerAddress> getCustomerAddresses() {
		return this.customerAddresses;
	}

	public void setCustomerAddresses(Set<CustomerAddress> customerAddresses) {
		this.customerAddresses = customerAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<EmployeeAddress> getEmployeeAddresses() {
		return this.employeeAddresses;
	}

	public void setEmployeeAddresses(Set<EmployeeAddress> employeeAddresses) {
		this.employeeAddresses = employeeAddresses;
	}

}
