package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerAddress generated by hbm2java
 */
@Entity
@Table(name = "customer_address", catalog = "carservice")
public class CustomerAddress implements java.io.Serializable {

	private int custAddressId;
	private AddressType addressType;
	private Customer customer;
	private City city;
	private String addressLine1;
	private String addressLine2;
	private Boolean sameAsPresent;
	private Integer zipcode;

	public CustomerAddress() {
	}

	public CustomerAddress(int custAddressId) {
		this.custAddressId = custAddressId;
	}

	public CustomerAddress(int custAddressId, AddressType addressType, Customer customer, City city,
			String addressLine1, String addressLine2, Boolean sameAsPresent, Integer zipcode) {
		this.custAddressId = custAddressId;
		this.addressType = addressType;
		this.customer = customer;
		this.city = city;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.sameAsPresent = sameAsPresent;
		this.zipcode = zipcode;
	}

	@Id

	@Column(name = "CUST_ADDRESS_ID", unique = true, nullable = false)
	public int getCustAddressId() {
		return this.custAddressId;
	}

	public void setCustAddressId(int custAddressId) {
		this.custAddressId = custAddressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_TYPE_ID")
	public AddressType getAddressType() {
		return this.addressType;
	}

	public void setAddressType(AddressType addressType) {
		this.addressType = addressType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITY_ID")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "ADDRESS_LINE1", length = 500)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2", length = 500)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "SAME_AS_PRESENT")
	public Boolean getSameAsPresent() {
		return this.sameAsPresent;
	}

	public void setSameAsPresent(Boolean sameAsPresent) {
		this.sameAsPresent = sameAsPresent;
	}

	@Column(name = "ZIPCODE")
	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

}
