package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomerDemandedRepairs generated by hbm2java
 */
@Entity
@Table(name = "customer_demanded_repairs", catalog = "carservice")
public class CustomerDemandedRepairs implements java.io.Serializable {

	private Integer custDemandedRepId;
	private String custDemandedRepName;

	public CustomerDemandedRepairs() {
	}

	public CustomerDemandedRepairs(String custDemandedRepName) {
		this.custDemandedRepName = custDemandedRepName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CUST_DEMANDED_REP_ID", unique = true, nullable = false)
	public Integer getCustDemandedRepId() {
		return this.custDemandedRepId;
	}

	public void setCustDemandedRepId(Integer custDemandedRepId) {
		this.custDemandedRepId = custDemandedRepId;
	}

	@Column(name = "CUST_DEMANDED_REP_NAME", length = 200)
	public String getCustDemandedRepName() {
		return this.custDemandedRepName;
	}

	public void setCustDemandedRepName(String custDemandedRepName) {
		this.custDemandedRepName = custDemandedRepName;
	}

}
