package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "carservice")
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private VechicalRegistration vechicalRegistration;
	private String customerName;
	private Set<CustomerAddress> customerAddresses = new HashSet<CustomerAddress>(0);
	private Set<CustomerEmail> customerEmails = new HashSet<CustomerEmail>(0);
	private Set<KeepInventory> keepInventories = new HashSet<KeepInventory>(0);
	private Set<CustomerPhone> customerPhones = new HashSet<CustomerPhone>(0);

	public Customer() {
	}

	public Customer(final VechicalRegistration vechicalRegistration, final String customerName,
			final Set<CustomerAddress> customerAddresses, final Set<CustomerEmail> customerEmails,
			final Set<KeepInventory> keepInventories, final Set<CustomerPhone> customerPhones) {
		this.vechicalRegistration = vechicalRegistration;
		this.customerName = customerName;
		this.customerAddresses = customerAddresses;
		this.customerEmails = customerEmails;
		this.keepInventories = keepInventories;
		this.customerPhones = customerPhones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CUSTOMER_ID", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(final Integer customerId) {
		this.customerId = customerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGISTRATION_ID")
	public VechicalRegistration getVechicalRegistration() {
		return this.vechicalRegistration;
	}

	public void setVechicalRegistration(final VechicalRegistration vechicalRegistration) {
		this.vechicalRegistration = vechicalRegistration;
	}

	@Column(name = "CUSTOMER_NAME", length = 30)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(final String customerName) {
		this.customerName = customerName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustomerAddress> getCustomerAddresses() {
		return this.customerAddresses;
	}

	public void setCustomerAddresses(final Set<CustomerAddress> customerAddresses) {
		this.customerAddresses = customerAddresses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustomerEmail> getCustomerEmails() {
		return this.customerEmails;
	}

	public void setCustomerEmails(final Set<CustomerEmail> customerEmails) {
		this.customerEmails = customerEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<KeepInventory> getKeepInventories() {
		return this.keepInventories;
	}

	public void setKeepInventories(final Set<KeepInventory> keepInventories) {
		this.keepInventories = keepInventories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<CustomerPhone> getCustomerPhones() {
		return this.customerPhones;
	}

	public void setCustomerPhones(final Set<CustomerPhone> customerPhones) {
		this.customerPhones = customerPhones;
	}

}
