package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustDemand generated by hbm2java
 */
@Entity
@Table(name = "cust_demand", catalog = "carservice")
public class CustDemand implements java.io.Serializable {

	private int custDemandId;
	private String custDemandName;

	public CustDemand() {
	}

	public CustDemand(int custDemandId) {
		this.custDemandId = custDemandId;
	}

	public CustDemand(int custDemandId, String custDemandName) {
		this.custDemandId = custDemandId;
		this.custDemandName = custDemandName;
	}

	@Id

	@Column(name = "cust_demand_id", unique = true, nullable = false)
	public int getCustDemandId() {
		return this.custDemandId;
	}

	public void setCustDemandId(int custDemandId) {
		this.custDemandId = custDemandId;
	}

	@Column(name = "cust_demand_name", length = 500)
	public String getCustDemandName() {
		return this.custDemandName;
	}

	public void setCustDemandName(String custDemandName) {
		this.custDemandName = custDemandName;
	}

}
