package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerPhone generated by hbm2java
 */
@Entity
@Table(name = "customer_phone", catalog = "carservice")
public class CustomerPhone implements java.io.Serializable {

	private Integer custPhoneId;
	private PhoneType phoneType;
	private Customer customer;
	private Integer phoneNo;

	public CustomerPhone() {
	}

	public CustomerPhone(PhoneType phoneType, Customer customer, Integer phoneNo) {
		this.phoneType = phoneType;
		this.customer = customer;
		this.phoneNo = phoneNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CUST_PHONE_ID", unique = true, nullable = false)
	public Integer getCustPhoneId() {
		return this.custPhoneId;
	}

	public void setCustPhoneId(Integer custPhoneId) {
		this.custPhoneId = custPhoneId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHONE_TYPE_ID")
	public PhoneType getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(PhoneType phoneType) {
		this.phoneType = phoneType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "PHONE_NO")
	public Integer getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(Integer phoneNo) {
		this.phoneNo = phoneNo;
	}

}
