package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CustomerEmail generated by hbm2java
 */
@Entity
@Table(name = "customer_email", catalog = "carservice")
public class CustomerEmail implements java.io.Serializable {

	private Integer custEmailId;
	private Customer customer;
	private EmailType emailType;
	private String email;

	public CustomerEmail() {
	}

	public CustomerEmail(Customer customer, EmailType emailType, String email) {
		this.customer = customer;
		this.emailType = emailType;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CUST_EMAIL_ID", unique = true, nullable = false)
	public Integer getCustEmailId() {
		return this.custEmailId;
	}

	public void setCustEmailId(Integer custEmailId) {
		this.custEmailId = custEmailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER_ID")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMAIL_TYPE_ID")
	public EmailType getEmailType() {
		return this.emailType;
	}

	public void setEmailType(EmailType emailType) {
		this.emailType = emailType;
	}

	@Column(name = "EMAIL", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
