package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeliveryStatusType generated by hbm2java
 */
@Entity
@Table(name = "delivery_status_type", catalog = "carservice")
public class DeliveryStatusType implements java.io.Serializable {

	private Integer deliveryStatusTypeId;
	private String deliveryStatusTypeName;
	private Set<Service> services = new HashSet<Service>(0);

	public DeliveryStatusType() {
	}

	public DeliveryStatusType(String deliveryStatusTypeName, Set<Service> services) {
		this.deliveryStatusTypeName = deliveryStatusTypeName;
		this.services = services;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DELIVERY_STATUS_TYPE_ID", unique = true, nullable = false)
	public Integer getDeliveryStatusTypeId() {
		return this.deliveryStatusTypeId;
	}

	public void setDeliveryStatusTypeId(Integer deliveryStatusTypeId) {
		this.deliveryStatusTypeId = deliveryStatusTypeId;
	}

	@Column(name = "DELIVERY_STATUS_TYPE_NAME", length = 100)
	public String getDeliveryStatusTypeName() {
		return this.deliveryStatusTypeName;
	}

	public void setDeliveryStatusTypeName(String deliveryStatusTypeName) {
		this.deliveryStatusTypeName = deliveryStatusTypeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deliveryStatusType")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
