package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DemandAdditionalJobDescription generated by hbm2java
 */
@Entity
@Table(name = "demand_additional_ job_description", catalog = "carservice")
public class DemandAdditionalJobDescription implements java.io.Serializable {

	private int demandId;
	private String jobDescription;
	private Integer qty;
	private Integer serviceCost;
	private Integer removeRefitLabourAmt;
	private Integer totalAmt;
	private byte[] photo;

	public DemandAdditionalJobDescription() {
	}

	public DemandAdditionalJobDescription(int demandId) {
		this.demandId = demandId;
	}

	public DemandAdditionalJobDescription(int demandId, String jobDescription, Integer qty, Integer serviceCost,
			Integer removeRefitLabourAmt, Integer totalAmt, byte[] photo) {
		this.demandId = demandId;
		this.jobDescription = jobDescription;
		this.qty = qty;
		this.serviceCost = serviceCost;
		this.removeRefitLabourAmt = removeRefitLabourAmt;
		this.totalAmt = totalAmt;
		this.photo = photo;
	}

	@Id

	@Column(name = "demand_id", unique = true, nullable = false)
	public int getDemandId() {
		return this.demandId;
	}

	public void setDemandId(int demandId) {
		this.demandId = demandId;
	}

	@Column(name = "job_description", length = 100)
	public String getJobDescription() {
		return this.jobDescription;
	}

	public void setJobDescription(String jobDescription) {
		this.jobDescription = jobDescription;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Column(name = "service_cost")
	public Integer getServiceCost() {
		return this.serviceCost;
	}

	public void setServiceCost(Integer serviceCost) {
		this.serviceCost = serviceCost;
	}

	@Column(name = "remove_refit_labour_amt")
	public Integer getRemoveRefitLabourAmt() {
		return this.removeRefitLabourAmt;
	}

	public void setRemoveRefitLabourAmt(Integer removeRefitLabourAmt) {
		this.removeRefitLabourAmt = removeRefitLabourAmt;
	}

	@Column(name = "total_amt")
	public Integer getTotalAmt() {
		return this.totalAmt;
	}

	public void setTotalAmt(Integer totalAmt) {
		this.totalAmt = totalAmt;
	}

	@Column(name = "photo")
	public byte[] getPhoto() {
		return this.photo;
	}

	public void setPhoto(byte[] photo) {
		this.photo = photo;
	}

}
