package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeRole generated by hbm2java
 */
@Entity
@Table(name = "employee_role", catalog = "carservice")
public class EmployeeRole implements java.io.Serializable {

	private int employeeRoleId;
	private Employee employee;
	private Status status;

	public EmployeeRole() {
	}

	public EmployeeRole(int employeeRoleId) {
		this.employeeRoleId = employeeRoleId;
	}

	public EmployeeRole(int employeeRoleId, Employee employee, Status status) {
		this.employeeRoleId = employeeRoleId;
		this.employee = employee;
		this.status = status;
	}

	@Id

	@Column(name = "EMPLOYEE_ROLE_ID", unique = true, nullable = false)
	public int getEmployeeRoleId() {
		return this.employeeRoleId;
	}

	public void setEmployeeRoleId(int employeeRoleId) {
		this.employeeRoleId = employeeRoleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS_ID")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

}
