package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeePhone generated by hbm2java
 */
@Entity
@Table(name = "employee_phone", catalog = "carservice")
public class EmployeePhone implements java.io.Serializable {

	private Integer employeePhoneId;
	private PhoneType phoneType;
	private Employee employee;
	private Integer phoneNo;

	public EmployeePhone() {
	}

	public EmployeePhone(PhoneType phoneType, Employee employee, Integer phoneNo) {
		this.phoneType = phoneType;
		this.employee = employee;
		this.phoneNo = phoneNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_PHONE_ID", unique = true, nullable = false)
	public Integer getEmployeePhoneId() {
		return this.employeePhoneId;
	}

	public void setEmployeePhoneId(Integer employeePhoneId) {
		this.employeePhoneId = employeePhoneId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PHONE_TYPE_ID")
	public PhoneType getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(PhoneType phoneType) {
		this.phoneType = phoneType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@Column(name = "PHONE_NO")
	public Integer getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(Integer phoneNo) {
		this.phoneNo = phoneNo;
	}

}
