package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeAddress generated by hbm2java
 */
@Entity
@Table(name = "employee_address", catalog = "carservice")
public class EmployeeAddress implements java.io.Serializable {

	private Integer employeeAddressId;
	private Employee employee;
	private AddressType addressType;
	private City city;
	private String addressLine1;
	private String addressLine2;
	private Boolean sameAsPresent;
	private Integer zipcode;

	public EmployeeAddress() {
	}

	public EmployeeAddress(Employee employee, AddressType addressType, City city, String addressLine1,
			String addressLine2, Boolean sameAsPresent, Integer zipcode) {
		this.employee = employee;
		this.addressType = addressType;
		this.city = city;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.sameAsPresent = sameAsPresent;
		this.zipcode = zipcode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_ADDRESS_ID", unique = true, nullable = false)
	public Integer getEmployeeAddressId() {
		return this.employeeAddressId;
	}

	public void setEmployeeAddressId(Integer employeeAddressId) {
		this.employeeAddressId = employeeAddressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_ID")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ADDRESS_TYPE_ID")
	public AddressType getAddressType() {
		return this.addressType;
	}

	public void setAddressType(AddressType addressType) {
		this.addressType = addressType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CITY_ID")
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "ADDRESS_LINE1", length = 500)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "ADDRESS_LINE2", length = 500)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "SAME_AS_PRESENT")
	public Boolean getSameAsPresent() {
		return this.sameAsPresent;
	}

	public void setSameAsPresent(Boolean sameAsPresent) {
		this.sameAsPresent = sameAsPresent;
	}

	@Column(name = "ZIPCODE")
	public Integer getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(Integer zipcode) {
		this.zipcode = zipcode;
	}

}
