package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmpoyeeIdProof generated by hbm2java
 */
@Entity
@Table(name = "empoyee_id_proof", catalog = "carservice")
public class EmpoyeeIdProof implements java.io.Serializable {

	private Integer employeeIdProofId;
	private IdProof idProof;
	private String idProofNo;

	public EmpoyeeIdProof() {
	}

	public EmpoyeeIdProof(IdProof idProof, String idProofNo) {
		this.idProof = idProof;
		this.idProofNo = idProofNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMPLOYEE_ID_PROOF_ID", unique = true, nullable = false)
	public Integer getEmployeeIdProofId() {
		return this.employeeIdProofId;
	}

	public void setEmployeeIdProofId(Integer employeeIdProofId) {
		this.employeeIdProofId = employeeIdProofId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_PROOF_ID")
	public IdProof getIdProof() {
		return this.idProof;
	}

	public void setIdProof(IdProof idProof) {
		this.idProof = idProof;
	}

	@Column(name = "ID_PROOF_NO", length = 50)
	public String getIdProofNo() {
		return this.idProofNo;
	}

	public void setIdProofNo(String idProofNo) {
		this.idProofNo = idProofNo;
	}

}
