package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Error generated by hbm2java
 */
@Entity
@Table(name = "error", catalog = "carservice")
public class Error implements java.io.Serializable {

	private Integer errorId;
	private String className;
	private String methodName;
	private String exceptionMessage;
	private String exceptionType;
	private Date exceptionDate;

	public Error() {
	}

	public Error(String className, String methodName, String exceptionMessage, String exceptionType,
			Date exceptionDate) {
		this.className = className;
		this.methodName = methodName;
		this.exceptionMessage = exceptionMessage;
		this.exceptionType = exceptionType;
		this.exceptionDate = exceptionDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ERROR_ID", unique = true, nullable = false)
	public Integer getErrorId() {
		return this.errorId;
	}

	public void setErrorId(Integer errorId) {
		this.errorId = errorId;
	}

	@Column(name = "CLASS_NAME", length = 200)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "METHOD_NAME", length = 50)
	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	@Column(name = "EXCEPTION_MESSAGE", length = 200)
	public String getExceptionMessage() {
		return this.exceptionMessage;
	}

	public void setExceptionMessage(String exceptionMessage) {
		this.exceptionMessage = exceptionMessage;
	}

	@Column(name = "EXCEPTION_TYPE", length = 100)
	public String getExceptionType() {
		return this.exceptionType;
	}

	public void setExceptionType(String exceptionType) {
		this.exceptionType = exceptionType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXCEPTION_DATE", length = 10)
	public Date getExceptionDate() {
		return this.exceptionDate;
	}

	public void setExceptionDate(Date exceptionDate) {
		this.exceptionDate = exceptionDate;
	}

}
