package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FuelType generated by hbm2java
 */
@Entity
@Table(name = "fuel_type", catalog = "carservice")
public class FuelType implements java.io.Serializable {

	private Integer fuelTypeId;
	private String fuelName;

	public FuelType() {
	}

	public FuelType(String fuelName) {
		this.fuelName = fuelName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "FUEL_TYPE_ID", unique = true, nullable = false)
	public Integer getFuelTypeId() {
		return this.fuelTypeId;
	}

	public void setFuelTypeId(Integer fuelTypeId) {
		this.fuelTypeId = fuelTypeId;
	}

	@Column(name = "FUEL_NAME", length = 10)
	public String getFuelName() {
		return this.fuelName;
	}

	public void setFuelName(String fuelName) {
		this.fuelName = fuelName;
	}

}
