package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IdProof generated by hbm2java
 */
@Entity
@Table(name = "id_proof", catalog = "carservice")
public class IdProof implements java.io.Serializable {

	private Integer idProofId;
	private String idProofName;
	private Set<EmpoyeeIdProof> empoyeeIdProofs = new HashSet<EmpoyeeIdProof>(0);

	public IdProof() {
	}

	public IdProof(String idProofName, Set<EmpoyeeIdProof> empoyeeIdProofs) {
		this.idProofName = idProofName;
		this.empoyeeIdProofs = empoyeeIdProofs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID_PROOF_ID", unique = true, nullable = false)
	public Integer getIdProofId() {
		return this.idProofId;
	}

	public void setIdProofId(Integer idProofId) {
		this.idProofId = idProofId;
	}

	@Column(name = "ID_PROOF_NAME", length = 500)
	public String getIdProofName() {
		return this.idProofName;
	}

	public void setIdProofName(String idProofName) {
		this.idProofName = idProofName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "idProof")
	public Set<EmpoyeeIdProof> getEmpoyeeIdProofs() {
		return this.empoyeeIdProofs;
	}

	public void setEmpoyeeIdProofs(Set<EmpoyeeIdProof> empoyeeIdProofs) {
		this.empoyeeIdProofs = empoyeeIdProofs;
	}

}
