package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InsideCar generated by hbm2java
 */
@Entity
@Table(name = "inside_car", catalog = "carservice")
public class InsideCar implements java.io.Serializable {

	private Integer insideCarId;
	private String insideCarName;

	public InsideCar() {
	}

	public InsideCar(String insideCarName) {
		this.insideCarName = insideCarName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "INSIDE_CAR_ID", unique = true, nullable = false)
	public Integer getInsideCarId() {
		return this.insideCarId;
	}

	public void setInsideCarId(Integer insideCarId) {
		this.insideCarId = insideCarId;
	}

	@Column(name = "INSIDE_CAR_NAME", length = 100)
	public String getInsideCarName() {
		return this.insideCarName;
	}

	public void setInsideCarName(String insideCarName) {
		this.insideCarName = insideCarName;
	}

}
