package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InsideHood generated by hbm2java
 */
@Entity
@Table(name = "inside_hood", catalog = "carservice")
public class InsideHood implements java.io.Serializable {

	private Integer insideHoodId;
	private String insideHoodName;

	public InsideHood() {
	}

	public InsideHood(String insideHoodName) {
		this.insideHoodName = insideHoodName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "INSIDE_HOOD_ID", unique = true, nullable = false)
	public Integer getInsideHoodId() {
		return this.insideHoodId;
	}

	public void setInsideHoodId(Integer insideHoodId) {
		this.insideHoodId = insideHoodId;
	}

	@Column(name = "INSIDE_HOOD_NAME", length = 100)
	public String getInsideHoodName() {
		return this.insideHoodName;
	}

	public void setInsideHoodName(String insideHoodName) {
		this.insideHoodName = insideHoodName;
	}

}
