package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * JobCard generated by hbm2java
 */
@Entity
@Table(name = "job_card", catalog = "carservice")
public class JobCard implements java.io.Serializable {

	private Integer jobCardId;
	private Service service;

	public JobCard() {
	}

	public JobCard(Service service) {
		this.service = service;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "JOB_CARD_ID", unique = true, nullable = false)
	public Integer getJobCardId() {
		return this.jobCardId;
	}

	public void setJobCardId(Integer jobCardId) {
		this.jobCardId = jobCardId;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "jobCard")
	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

}
