package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Make generated by hbm2java
 */
@Entity
@Table(name = "make", catalog = "carservice")
public class Make implements java.io.Serializable {

	private Integer makeId;
	private String makeName;
	private Set<Model> models = new HashSet<Model>(0);

	public Make() {
	}

	public Make(String makeName, Set<Model> models) {
		this.makeName = makeName;
		this.models = models;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MAKE_ID", unique = true, nullable = false)
	public Integer getMakeId() {
		return this.makeId;
	}

	public void setMakeId(Integer makeId) {
		this.makeId = makeId;
	}

	@Column(name = "MAKE_NAME", length = 200)
	public String getMakeName() {
		return this.makeName;
	}

	public void setMakeName(String makeName) {
		this.makeName = makeName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "make")
	public Set<Model> getModels() {
		return this.models;
	}

	public void setModels(Set<Model> models) {
		this.models = models;
	}

}
