package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Model generated by hbm2java
 */
@Entity
@Table(name = "model", catalog = "carservice")
public class Model implements java.io.Serializable {

	private Integer modelId;
	private Make make;
	private String modelName;

	public Model() {
	}

	public Model(Make make, String modelName) {
		this.make = make;
		this.modelName = modelName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MODEL_ID", unique = true, nullable = false)
	public Integer getModelId() {
		return this.modelId;
	}

	public void setModelId(Integer modelId) {
		this.modelId = modelId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MAKE_ID")
	public Make getMake() {
		return this.make;
	}

	public void setMake(Make make) {
		this.make = make;
	}

	@Column(name = "MODEL_NAME", length = 200)
	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

}
