package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OutsideCar generated by hbm2java
 */
@Entity
@Table(name = "outside_car", catalog = "carservice")
public class OutsideCar implements java.io.Serializable {

	private Integer outsideCarId;
	private String outsideCarName;

	public OutsideCar() {
	}

	public OutsideCar(String outsideCarName) {
		this.outsideCarName = outsideCarName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OUTSIDE_CAR_ID", unique = true, nullable = false)
	public Integer getOutsideCarId() {
		return this.outsideCarId;
	}

	public void setOutsideCarId(Integer outsideCarId) {
		this.outsideCarId = outsideCarId;
	}

	@Column(name = "OUTSIDE_CAR_NAME", length = 100)
	public String getOutsideCarName() {
		return this.outsideCarName;
	}

	public void setOutsideCarName(String outsideCarName) {
		this.outsideCarName = outsideCarName;
	}

}
