package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Security generated by hbm2java
 */
@Entity
@Table(name = "security", catalog = "carservice")
public class Security implements java.io.Serializable {

	private Integer securityId;
	private Role role;
	private String applicationName;

	public Security() {
	}

	public Security(Role role, String applicationName) {
		this.role = role;
		this.applicationName = applicationName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SECURITY_ID", unique = true, nullable = false)
	public Integer getSecurityId() {
		return this.securityId;
	}

	public void setSecurityId(Integer securityId) {
		this.securityId = securityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROLE_ID")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "APPLICATION_NAME", length = 200)
	public String getApplicationName() {
		return this.applicationName;
	}

	public void setApplicationName(String applicationName) {
		this.applicationName = applicationName;
	}

}
