package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "carservice")
public class Service implements java.io.Serializable {

	private int jobCardId;
	private DeliveryStatusType deliveryStatusType;
	private JobCard jobCard;
	private VechicalRegistration vechicalRegistration;
	private Integer fuelGauge;
	private Integer kmReading;
	private byte[] damage;
	private Integer custDemandedRepId;
	private Date deliveryDate;

	public Service() {
	}

	public Service(JobCard jobCard) {
		this.jobCard = jobCard;
	}

	public Service(DeliveryStatusType deliveryStatusType, JobCard jobCard, VechicalRegistration vechicalRegistration,
			Integer fuelGauge, Integer kmReading, byte[] damage, Integer custDemandedRepId, Date deliveryDate) {
		this.deliveryStatusType = deliveryStatusType;
		this.jobCard = jobCard;
		this.vechicalRegistration = vechicalRegistration;
		this.fuelGauge = fuelGauge;
		this.kmReading = kmReading;
		this.damage = damage;
		this.custDemandedRepId = custDemandedRepId;
		this.deliveryDate = deliveryDate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "jobCard"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "JOB_CARD_ID", unique = true, nullable = false)
	public int getJobCardId() {
		return this.jobCardId;
	}

	public void setJobCardId(int jobCardId) {
		this.jobCardId = jobCardId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATUS")
	public DeliveryStatusType getDeliveryStatusType() {
		return this.deliveryStatusType;
	}

	public void setDeliveryStatusType(DeliveryStatusType deliveryStatusType) {
		this.deliveryStatusType = deliveryStatusType;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public JobCard getJobCard() {
		return this.jobCard;
	}

	public void setJobCard(JobCard jobCard) {
		this.jobCard = jobCard;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGISTRATION_ID")
	public VechicalRegistration getVechicalRegistration() {
		return this.vechicalRegistration;
	}

	public void setVechicalRegistration(VechicalRegistration vechicalRegistration) {
		this.vechicalRegistration = vechicalRegistration;
	}

	@Column(name = "FUEL_GAUGE")
	public Integer getFuelGauge() {
		return this.fuelGauge;
	}

	public void setFuelGauge(Integer fuelGauge) {
		this.fuelGauge = fuelGauge;
	}

	@Column(name = "KM_READING")
	public Integer getKmReading() {
		return this.kmReading;
	}

	public void setKmReading(Integer kmReading) {
		this.kmReading = kmReading;
	}

	@Column(name = "DAMAGE")
	public byte[] getDamage() {
		return this.damage;
	}

	public void setDamage(byte[] damage) {
		this.damage = damage;
	}

	@Column(name = "CUST_DEMANDED_REP_ID")
	public Integer getCustDemandedRepId() {
		return this.custDemandedRepId;
	}

	public void setCustDemandedRepId(Integer custDemandedRepId) {
		this.custDemandedRepId = custDemandedRepId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DELIVERY_DATE", length = 19)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

}
