package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UnderBody generated by hbm2java
 */
@Entity
@Table(name = "under_body", catalog = "carservice")
public class UnderBody implements java.io.Serializable {

	private Integer underBodyId;
	private String underBodyName;

	public UnderBody() {
	}

	public UnderBody(String underBodyName) {
		this.underBodyName = underBodyName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UNDER_BODY_ID", unique = true, nullable = false)
	public Integer getUnderBodyId() {
		return this.underBodyId;
	}

	public void setUnderBodyId(Integer underBodyId) {
		this.underBodyId = underBodyId;
	}

	@Column(name = "UNDER_BODY_NAME", length = 100)
	public String getUnderBodyName() {
		return this.underBodyName;
	}

	public void setUnderBodyName(String underBodyName) {
		this.underBodyName = underBodyName;
	}

}
