package com.mfc.to;
// Generated Nov 25, 2017 7:35:24 PM by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VechicalRegistration generated by hbm2java
 */
@Entity
@Table(name = "vechical_registration", catalog = "carservice")
public class VechicalRegistration implements java.io.Serializable {

	private String registrationId;
	private String engineNo;
	private String chassisNo;
	private String modelId;
	private Integer fuelId;
	private Set<Customer> customers = new HashSet<Customer>(0);
	private Set<Service> services = new HashSet<Service>(0);

	public VechicalRegistration() {
	}

	public VechicalRegistration(String registrationId) {
		this.registrationId = registrationId;
	}

	public VechicalRegistration(String registrationId, String engineNo, String chassisNo, String modelId,
			Integer fuelId, Set<Customer> customers, Set<Service> services) {
		this.registrationId = registrationId;
		this.engineNo = engineNo;
		this.chassisNo = chassisNo;
		this.modelId = modelId;
		this.fuelId = fuelId;
		this.customers = customers;
		this.services = services;
	}

	@Id

	@Column(name = "REGISTRATION_ID", unique = true, nullable = false, length = 50)
	public String getRegistrationId() {
		return this.registrationId;
	}

	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId;
	}

	@Column(name = "ENGINE_NO", length = 50)
	public String getEngineNo() {
		return this.engineNo;
	}

	public void setEngineNo(String engineNo) {
		this.engineNo = engineNo;
	}

	@Column(name = "CHASSIS_NO", length = 50)
	public String getChassisNo() {
		return this.chassisNo;
	}

	public void setChassisNo(String chassisNo) {
		this.chassisNo = chassisNo;
	}

	@Column(name = "MODEL_ID", length = 50)
	public String getModelId() {
		return this.modelId;
	}

	public void setModelId(String modelId) {
		this.modelId = modelId;
	}

	@Column(name = "FUEL_ID")
	public Integer getFuelId() {
		return this.fuelId;
	}

	public void setFuelId(Integer fuelId) {
		this.fuelId = fuelId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vechicalRegistration")
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vechicalRegistration")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
